#!/bin/sh
# Reads GOOGLE_IOS_CLIENT_ID from apps/mobile/.env and writes:
#   - Flutter/GoogleSignIn.xcconfig (build settings)
#   - Runner/Info.plist GIDClientID + URL scheme (literal — Xcode was not
#     expanding $(GID_URL_SCHEME) into the installed Info.plist)
set -e

SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
IOS_ROOT="$(CDPATH= cd -- "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="${IOS_ROOT}/../.env"
OUT_FILE="${SCRIPT_DIR}/GoogleSignIn.xcconfig"
INFO_PLIST="${IOS_ROOT}/Runner/Info.plist"

write_xcconfig() {
  cat >"$OUT_FILE" <<EOF
// Auto-generated by sync_google_sign_in.sh — do not edit.
GID_CLIENT_ID=$1
GID_URL_SCHEME=$2
EOF
}

apply_info_plist() {
  client_id="$1"
  url_scheme="$2"
  /usr/libexec/PlistBuddy -c "Delete :GIDClientID" "$INFO_PLIST" 2>/dev/null || true
  /usr/libexec/PlistBuddy -c "Add :GIDClientID string ${client_id}" "$INFO_PLIST"
  /usr/libexec/PlistBuddy -c "Delete :CFBundleURLTypes" "$INFO_PLIST" 2>/dev/null || true
  /usr/libexec/PlistBuddy -c "Add :CFBundleURLTypes array" "$INFO_PLIST"
  /usr/libexec/PlistBuddy -c "Add :CFBundleURLTypes:0 dict" "$INFO_PLIST"
  /usr/libexec/PlistBuddy -c "Add :CFBundleURLTypes:0:CFBundleTypeRole string Editor" "$INFO_PLIST"
  /usr/libexec/PlistBuddy -c "Add :CFBundleURLTypes:0:CFBundleURLSchemes array" "$INFO_PLIST"
  /usr/libexec/PlistBuddy -c "Add :CFBundleURLTypes:0:CFBundleURLSchemes:0 string ${url_scheme}" "$INFO_PLIST"
}

if [ ! -f "$ENV_FILE" ]; then
  echo "warning: $ENV_FILE missing; Google Sign-In iOS config not set" >&2
  write_xcconfig "" ""
  exit 0
fi

IOS_CLIENT_ID=$(grep -E '^[[:space:]]*GOOGLE_IOS_CLIENT_ID=' "$ENV_FILE" | head -1 | cut -d= -f2- | tr -d '"' | tr -d "'" | tr -d '[:space:]')

if [ -z "$IOS_CLIENT_ID" ] || [ "$IOS_CLIENT_ID" = "123456789-yyyy.apps.googleusercontent.com" ]; then
  echo "warning: set GOOGLE_IOS_CLIENT_ID in apps/mobile/.env for Google Sign-In on iOS" >&2
  write_xcconfig "" ""
  exit 0
fi

case "$IOS_CLIENT_ID" in
  *.apps.googleusercontent.com)
    ID_PART="${IOS_CLIENT_ID%.apps.googleusercontent.com}"
  ;;
  *)
    echo "error: GOOGLE_IOS_CLIENT_ID must end with .apps.googleusercontent.com" >&2
    exit 1
  ;;
esac

GID_URL_SCHEME="com.googleusercontent.apps.${ID_PART}"

write_xcconfig "$IOS_CLIENT_ID" "$GID_URL_SCHEME"
apply_info_plist "$IOS_CLIENT_ID" "$GID_URL_SCHEME"

echo "Google Sign-In iOS config synced (xcconfig + Info.plist URL scheme)"
